# Generated by Django 4.1.2 on 2022-12-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_email', models.CharField(max_length=100)),
                ('customer_address', models.CharField(max_length=500)),
                ('customer_mobile', models.CharField(max_length=15)),
            ],
        ),
    ]
