# Generated by Django 4.1.2 on 2022-12-08 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_order_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.product'),
        ),
    ]
