# Generated by Django 4.1.4 on 2023-01-06 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_orderdetails_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product_id',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderDetails',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
