# Generated by Django 4.1.4 on 2022-12-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_apis', '0002_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='subtotal',
            field=models.IntegerField(default=0),
        ),
    ]
