# Generated by Django 4.1.4 on 2023-01-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=10)),
                ('otp', models.CharField(blank=True, max_length=6)),
                ('otp_expiry', models.DateTimeField(blank=True)),
            ],
        ),
    ]
